### PR TITLE
fix the broken script that downloads the weekly report.

### PR DESCRIPTION
**Pull request by boyi**
fix the broken script that downloads the weekly report.

### CODE REVIEW

**Comment by majdiCalboussi** [comment]
doesn't work. still download the weekly report of this week only.

**Comment by TopGun1024** [comment]
Did anyone get this to work?  Still having issues (although they are different now).  I just get messages now that daily reports aren't available.

**Comment by lbast** [comment]
TopGun1024 - same here. We've sort of given up on this script, and are using Appfigures API instead. Just FYI.

**Comment by TopGun1024** [comment]
Thanks for the confirmation.  AppFigures doesn't give data per-product, per-country, per-date which is a requirement of our system.

**Comment by majdiCalboussi** [comment]
hi @TopGun1024 and @lbast . the last modification made by @boyi is working perfectly. you must remove lines 357, 358 and 359 and replace them by this code :

---

c = int(dailyName[-4])
c = (c + 1) % 10
ajaxName = dailyName[:-4] + str(c) + '_2'
dateName = dailyName[:-4] + str(c) + '_8'
selectName = dailyName[:-4] + str(c) + '_30'
ajaxName = re.sub('._51', '3_2', dailyName)
dateName = re.sub('._51', '3_8', dailyName)
selectName = re.sub('._51', '3_30', dailyName)

---

here is the link that show modifications https://github.com/boyi/appdailysales/commit/6818333e6e88ac7f4cc270536fd1174c6649e946

**Comment by TopGun1024** [comment]
Thanks for the info - when I looked at the diff (and again in the link you provided), the last three lines above look  commented out.  I've tried it both ways, to no avail.

**Comment by majdiCalboussi** [comment]
@TopGun1024 my bed if you look at the file at https://github.com/kirbyt/appdailysales/blob/master/appdailysales.py it was updated correctly. are you trying to download with -D option or with the -d ? what do you get as file name if you execute with -D 1 ?

**Comment by TopGun1024** [comment]
I'm specifying the exact date with:

-D 05/17/2012

And I get the following response:

05/17/2012 report is not available - try again later.
1 report(s) not available - try again later

Thanks for your help!

**Comment by majdiCalboussi** [comment]
@TopGun1024 try to you '-d 5' cause -D wasn't fixed yet. please keep me informed. and you are welcome ;)

**Comment by kirbyt** [comment]
I went with the pull request from @staufman which fixes the same issue.

**Pull request closed without merging**
